/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.30
 * Generated at: 2018-04-28 09:49:42 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.user;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class userList_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1522375494000L));
    _jspx_dependants.put("jar:file:/Users/bob/Documents/Workplace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/lands/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153349082000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.release();
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/views/include/header.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/resources/css/bootstrap.min.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/resources/css/bootstrap-responsive.min.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/resources/css/colorpicker.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/resources/css/datepicker.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/resources/css/uniform.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/resources/css/select2.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/resources/css/matrix-style.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/resources/css/matrix-media.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/resources/css/bootstrap-wysihtml5.css\" />\r\n");
      out.write("<link href=\"/resources/font-awesome/css/font-awesome.css\" rel=\"stylesheet\" />\r\n");
      out.write("<link href='http://fonts.googleapis.com/css?family=Open+Sans:400,700,800' rel='stylesheet' type='text/css'>\r\n");
      out.write("\r\n");
      out.write("<script src=\"/resources/js/jquery.ui.custom.js\"></script> \r\n");
      out.write("<script src=\"/resources/js/bootstrap.min.js\"></script> \r\n");
      out.write("<script src=\"/resources/js/bootstrap-colorpicker.js\"></script> \r\n");
      out.write("<script src=\"/resources/js/bootstrap-datepicker.js\"></script> \r\n");
      out.write("<script src=\"/resources/js/jquery.sparkline.min.js\"></script>\r\n");
      out.write("<script src=\"/resources/js/jquery.toggle.buttons.js\"></script> \r\n");
      out.write("<script src=\"/resources/js/masked.js\"></script> \r\n");
      out.write("<script src=\"/resources/js/jquery.uniform.js\"></script> \r\n");
      out.write("<script src=\"/resources/js/select2.min.js\"></script> \r\n");
      out.write("<script src=\"/resources/js/matrix.js\"></script> \r\n");
      out.write("<script src=\"/resources/js/wysihtml5-0.3.0.js\"></script> \r\n");
      out.write("<script src=\"/resources/js/jquery.peity.min.js\"></script> \r\n");
      out.write("<script src=\"/resources/js/bootstrap-wysihtml5.js\"></script> \r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("\tvar mIntDifference = 30;\r\n");
      out.write("\tvar mIntOffset = 0;\r\n");
      out.write("\tvar mIntTotalTdCount = 0;\t//전체 테이블 개수 더보기 기능\r\n");
      out.write("\tvar mArrTbData = [];\t\t//테이블 데이터 저장\r\n");
      out.write("\tvar mStrBeforeBG = \"\";\t\t//td 클릭시 전에 클릭했던 백그라운드 저장\r\n");
      out.write("\tvar mStrBeforeId = \"\";\t\t//td 클릭시 전에 클릭했던 ID 저장\r\n");
      out.write("\tvar mIntUpdtDataNo = \"\";\t//클릭 된 td의 PK NO\r\n");
      out.write("\tvar mStrClickable = \"Y\";\t//클릭 가능한지 상태를 보여주는 변수\r\n");
      out.write("\tvar mStrInsStatus = \"\";\t//Save 버튼을 업데이트와 같이 쓰기 때문에 새로 추가 할때 저장은 다른 status를 주기 위해 사용하는 변수\r\n");
      out.write("\t");

		String mStrUserId = (String)session.getAttribute("userId");
	
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\tfunction doCodeDetail(strCommName, strCommCode){\r\n");
      out.write("\t\tvar strReturnVal = \"\";\r\n");
      out.write("\t\t");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\treturn strReturnVal\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction doSelectData(strValue){\r\n");
      out.write("\t\t$(\"#btnMore\").show();\r\n");
      out.write("\t\t$(\"#ftLoading\").show();\r\n");
      out.write("\t\t$(\".inpData\").val(\"\");\r\n");
      out.write("\t\t$(\"#\"+mStrBeforeId).css(\"background-color\",mStrBeforeBG);\r\n");
      out.write("\t\t$(\"#btnPw\").attr(\"disabled\",true);\r\n");
      out.write("\t\tmStrClickable = \"Y\";\r\n");
      out.write("\t\tdoCancel();\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tif(strValue == \"M\") {\r\n");
      out.write("\t\t\tmIntOffset += mIntDifference;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tif(strValue != \"M\") {\r\n");
      out.write("\t\t\tmIntOffset = 0;\r\n");
      out.write("\t\t\t$(\"#tblUserList tr\").remove();\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\r\n");
      out.write("\t\tvar objData = {};\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t/* objData[\"strUserName\"] = $(\"#inpUserName\").val();\r\n");
      out.write("\t\tobjData[\"strSDate\"] = strSDate;\r\n");
      out.write("\t\tobjData[\"strEDate\"] = strEDate;*/\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tobjData[\"intOffset\"] = mIntOffset;\r\n");
      out.write("\t\tobjData[\"intDifference\"] = mIntDifference;\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\ttype: \"POST\",\r\n");
      out.write("\t\t\turl: \"/user/admin/getUserList.do\",\r\n");
      out.write("\t\t\tcontentType: \"application/json; charset=UTF-8\",\r\n");
      out.write("\t\t\tdata: JSON.stringify(objData),\r\n");
      out.write("\t\t\tdataType: \"JSON\",\r\n");
      out.write("\t\t\tsuccess: function(arrReturnVal) {\r\n");
      out.write("\t\t\t\tdoSelectDataHandler(arrReturnVal);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction doSelectDataHandler(arrReturnVal) {\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t//M1 -> Minus 1\r\n");
      out.write("\t\t//1을 빼는 이유는 마지막 배열에 TOTAL_ROW_COUNT가 같이 오기 때문\r\n");
      out.write("\t\tvar intArrSizeM1 = arrReturnVal.length-1;\r\n");
      out.write("\t\tvar intTotalRowCount = arrReturnVal[intArrSizeM1].TOTAL_ROW_COUNT;\r\n");
      out.write("\t\tvar arrHtml = [];\r\n");
      out.write("\t\tif(intArrSizeM1 == 0) {\r\n");
      out.write("\t\t\t$(\"#btnMore\").hide();\r\n");
      out.write("\t\t\tarrHtml.push('<tr class=\"odd\"><td valign=\"top\" colspan=\"4\" class=\"dataTables_empty\">No data available in table</td></tr>');\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\telse {\r\n");
      out.write("\t\t\tvar strUmNo = \"\";\r\n");
      out.write("\t\t\tvar strUserId = \"\";\r\n");
      out.write("\t\t\tvar strUserPw = \"\";\r\n");
      out.write("\t\t\tvar strUserName = \"\";\r\n");
      out.write("\t\t\tvar strUserEmail = \"\";\r\n");
      out.write("\t\t\tvar strUserBDay = \"\";\r\n");
      out.write("\t\t\tvar strAuth = \"\";\r\n");
      out.write("\t\t\tvar strUserLvl = \"\";\r\n");
      out.write("\t\t\tvar strDmNoSq = \"\";\r\n");
      out.write("\t\t\tvar strUseYn = \"\";\r\n");
      out.write("\t\t\tvar strRegId = \"\";\r\n");
      out.write("\t\t\tvar strRegIp = \"\";\r\n");
      out.write("\t\t\tvar strRegDate = \"\";\r\n");
      out.write("\t\t\tvar strUpdtId = \"\";\r\n");
      out.write("\t\t\tvar strUpdtIp = \"\";\r\n");
      out.write("\t\t\tvar strUpdtDate = \"\";\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t//arrReturnVal.length -1 하는 이유는 마지막 밸류는 항상 TOTAL_ROW_COUNT 이기 때문이다.\r\n");
      out.write("\t\t\tfor(var intIndex = 0; intIndex < intArrSizeM1; intIndex++) {\r\n");
      out.write("\t\t\t\t//더보기 기능\r\n");
      out.write("\t\t\t\tmIntTotalTdCount++;\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tstrUmNo\t\t\t= arrReturnVal[intIndex].UM_NO_SQ_PK;\r\n");
      out.write("\t\t\t\tstrUserId\t\t= arrReturnVal[intIndex].USER_ID;\r\n");
      out.write("\t\t\t\tstrUserPw\t\t= arrReturnVal[intIndex].USER_PW;\r\n");
      out.write("\t\t\t\tstrUserName\t\t= arrReturnVal[intIndex].USER_NAME;\r\n");
      out.write("\t\t\t\tstrUserEmail\t= arrReturnVal[intIndex].USER_EMAIL== null ? \"\" : arrReturnVal[intIndex].USER_EMAIL;\r\n");
      out.write("\t\t\t\tstrUserBDay\t\t= arrReturnVal[intIndex].USER_BDAY== null ? \"\" : arrReturnVal[intIndex].USER_BDAY;\r\n");
      out.write("\t\t\t\tstrAuth\t\t\t= doCodeDetail(\"USER_AUTH\",arrReturnVal[intIndex].USER_AUTH);\r\n");
      out.write("\t\t\t\tstrLvl\t\t\t= doCodeDetail(\"USER_LVL\",arrReturnVal[intIndex].USER_LVL);\r\n");
      out.write("\t\t\t\tstrDmNoSq\t\t= arrReturnVal[intIndex].DM_NO_SQ== null ? \"\" : arrReturnVal[intIndex].DM_NO_SQ;\r\n");
      out.write("\t\t\t\tstrUseYn\t\t= arrReturnVal[intIndex].USE_YN;\r\n");
      out.write("\t\t\t\tstrRegId\t\t= arrReturnVal[intIndex].REG_ID;\r\n");
      out.write("\t\t\t\tstrRegIp\t\t= arrReturnVal[intIndex].REG_IP;\r\n");
      out.write("\t\t\t\tstrRegDate\t\t= arrReturnVal[intIndex].REG_DATE;\r\n");
      out.write("\t\t\t\tstrUpdtId\t\t= arrReturnVal[intIndex].UPDT_ID == null ? \"\" : arrReturnVal[intIndex].UPDT_ID;\r\n");
      out.write("\t\t\t\tstrUpdtIp\t\t= arrReturnVal[intIndex].UPDT_IP == null ? \"\" : arrReturnVal[intIndex].UPDT_IP;\r\n");
      out.write("\t\t\t\tstrUpdtDate\t\t= arrReturnVal[intIndex].UPDT_DATE == null ? \"\" : arrReturnVal[intIndex].UPDT_DATE;\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tif(intIndex % 2 == 0){\r\n");
      out.write("\t\t\t\t\t\tarrHtml.push(\"<tr id='trData\"+strUmNo+\"' class='trData' style='background-color:#f9f9f9;\");\r\n");
      out.write("\t\t\t\t\t\tif(strUseYn == \"N\")\tarrHtml.push(\"color:red;\");\r\n");
      out.write("\t\t\t\t\t\tarrHtml.push(\"' onclick='trOnClick(\\\"trData\"+strUmNo+\"\\\",\"+strUmNo+\");'>\");\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\telse{\r\n");
      out.write("\t\t\t\t\tarrHtml.push(\"<tr id='trData\"+strUmNo+\"' class='trData' style='background-color:white;\");\r\n");
      out.write("\t\t\t\t\tif(strUseYn ==\"N\") arrHtml.push(\"color:red;\");\r\n");
      out.write("\t\t\t\t\tarrHtml.push(\"' onclick='trOnClick(\\\"trData\"+strUmNo+\"\\\",\"+strUmNo+\");'>\");\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t/* arrHtml.push(\"<td class='tdTextCenter'>\"+ strUmNo +\"</td>\"); */\r\n");
      out.write("\t\t\t\t\tarrHtml.push(\"<td class='tdTextCenter'>\"+ strUserId +\"</td>\");\r\n");
      out.write("\t\t\t\t\tarrHtml.push(\"<td class='tdTextCenter' style='display:none;'>\"+ strUserPw +\"</td>\");\r\n");
      out.write("\t\t\t\t\tarrHtml.push(\"<td class='tdTextCenter'>\"+ strUserName +\"</td>\");\r\n");
      out.write("\t\t\t\t\tarrHtml.push(\"<td class='tdTextCenter'>\"+ strUserEmail +\"</td>\");\r\n");
      out.write("\t\t\t\t\tarrHtml.push(\"<td class='tdTextCenter'>\"+ strUserBDay +\"</td>\");\r\n");
      out.write("\t\t\t\t\tarrHtml.push(\"<td class='tdTextCenter'>\"+ strAuth +\"</td>\");\r\n");
      out.write("\t\t\t\t\tarrHtml.push(\"<td class='tdTextCenter'>\"+ strLvl +\"</td>\");\r\n");
      out.write("\t\t\t\t\tarrHtml.push(\"<td class='tdTextCenter' id='tdTypeNo\"+strUmNo+\"'\t>\");\r\n");
      out.write("\t\t\t\t\tif(!checkNullHd(strDmNoSq)){\r\n");
      out.write("\t\t\t\t\t\tarrHtml.push(\"<button type='button' class='btn btn-secondary' onclick='doSelectDealerData(\"+strDmNoSq+\");' style='font-size:11px;'>show</button>\");\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\tarrHtml.push(\"</td>\");\r\n");
      out.write("\t\t\t\t\tarrHtml.push(\"<td class='tdTextCenter'>\"+ strUseYn +\"</td>\");\r\n");
      out.write("\t\t\t\t\tarrHtml.push(\"<td class='tdTextCenter'>\"+ strRegId +\"</td>\");\r\n");
      out.write("\t\t\t\t\tarrHtml.push(\"<td class='tdTextCenter'>\"+ strRegIp +\"</td>\");\r\n");
      out.write("\t\t\t\t\tarrHtml.push(\"<td class='tdTextCenter'>\"+ strRegDate +\"</td>\");\r\n");
      out.write("\t\t\t\t\tarrHtml.push(\"<td class='tdTextCenter'>\"+ strUpdtId +\"</td>\");\r\n");
      out.write("\t\t\t\t\tarrHtml.push(\"<td class='tdTextCenter'>\"+ strUpdtIp +\"</td>\");\r\n");
      out.write("\t\t\t\t\tarrHtml.push(\"<td class='tdTextCenter'>\"+ strUpdtDate +\"</td>\");\r\n");
      out.write("\t\t\t\tarrHtml.push(\"</tr>\");\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t//더보기 기능(무한스크롤) remove\r\n");
      out.write("\t\t\tif(intArrSizeM1 != mIntDifference || mIntTotalTdCount == intTotalRowCount) {\r\n");
      out.write("\t\t\t\t$(\"#btnMore\").hide();\r\n");
      out.write("\t\t\t\tarrHtml.push('<tr class=\"odd\"><td valign=\"top\" colspan=\"14\" class=\"dataTables_empty\" style=\"text-align:center;\">END</td></tr>');\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(\"#tblUserList\").append(arrHtml.join(\"\"));\r\n");
      out.write("\t\t$(\"#ftLoading\").hide();\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction doSelectDealerData(strDmNoSq) {\r\n");
      out.write("\t\t$(\"#ftLoading\").show();\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar objData = {};\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tobjData[\"dmNoSq\"] = strDmNoSq;\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\ttype: \"POST\",\r\n");
      out.write("\t\t\turl: \"/user/admin/getDealerInfo.do\",\r\n");
      out.write("\t\t\tcontentType: \"application/json; charset=UTF-8\",\r\n");
      out.write("\t\t\tdata: JSON.stringify(objData),\r\n");
      out.write("\t\t\tdataType: \"JSON\",\r\n");
      out.write("\t\t\tsuccess: function(arrReturnVal) {\r\n");
      out.write("\t\t\t\tdoSelectDealerDataHandler(arrReturnVal);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction doSelectDealerDataHandler(arrReturnVal){\r\n");
      out.write("\t\t$(\".trDealerInfo\").remove();\r\n");
      out.write("\r\n");
      out.write("\t\tvar arrHtml = [];\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar strDmNoSqPk\t\t= arrReturnVal[0].DM_NO_SQ_PK;\r\n");
      out.write("\t\tvar strScores\t\t= arrReturnVal[0].DEALER_SCORES;\r\n");
      out.write("\t\tvar strCancelCnt\t= arrReturnVal[0].DEALER_CANCEL_CNT;\r\n");
      out.write("\t\tvar strPoint\t\t= arrReturnVal[0].DEALER_POINT;\r\n");
      out.write("\t\tvar strFeedbackYn\t= arrReturnVal[0].DEALER_FEEDBACK_YN;\r\n");
      out.write("\t\tvar strRemark1\t\t= checkNullHd(arrReturnVal[0].REMARK1)? \"\": arrReturnVal[0].REMARK1;\r\n");
      out.write("\t\tvar strRemark2\t\t= checkNullHd(arrReturnVal[0].REMARK2)? \"\": arrReturnVal[0].REMARK2;\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tarrHtml.push(\"<div id='trData\"+strDmNoSqPk+\"' class='trData trDealerInfo' style='background-color:white;' onclick='trOnClick(\\\"trData\"+strDmNoSqPk+\"\\\",\"+strDmNoSqPk+\");'>\");\r\n");
      out.write("\t\t\tarrHtml.push(\"<div class='tdTextCenter marginTop10px'>SCORES : \"+ strScores +\"</div>\");\r\n");
      out.write("\t\t\tarrHtml.push(\"<div class='tdTextCenter marginTop10px'>CANCEL CNT : \"+ strCancelCnt +\"</div>\");\r\n");
      out.write("\t\t\tarrHtml.push(\"<div class='tdTextCenter marginTop10px'>POINTS : \"+ strPoint +\"</div>\");\r\n");
      out.write("\t\t\tarrHtml.push(\"<div class='tdTextCenter marginTop10px'>FEEDBACK YN : \"+ strFeedbackYn +\"</div>\");\r\n");
      out.write("\t\t\tarrHtml.push(\"<div class='tdTextCenter marginTop10px'>\"+ strRemark1 +\"</div>\");\r\n");
      out.write("\t\t\tarrHtml.push(\"<div class='tdTextCenter marginTop10px'>\"+ strRemark2 +\"</div>\");\r\n");
      out.write("\t\tarrHtml.push(\"</div>\");\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tconsole.log(JSON.stringify(arrHtml));\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(\"#modalBody\").append(arrHtml.join(\"\"));\r\n");
      out.write("\t\t$(\"#ftLoading\").hide();\r\n");
      out.write("\t\t$(\"#btnDealerInfo\").click();\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction doUpdateData(strType){\r\n");
      out.write("\t\t$(\"#ftLoading\").show();\r\n");
      out.write("\t\tvar objData = {};\r\n");
      out.write("\t\tvar strUrl = \"\";\r\n");
      out.write("\t\tobjData[\"umNoSqPk\"] = mIntUpdtDataNo;\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tif(strType == \"I\") {\r\n");
      out.write("\t\t\tif(!doCheckValidation()) {\r\n");
      out.write("\t\t\t\t//alert(\"Check your data. (Save failed!)\");\r\n");
      out.write("\t\t\t\t$(\"#ftLoading\").hide();\r\n");
      out.write("\t\t\t\treturn;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tif(mStrInsStatus == \"I\"){\r\n");
      out.write("\t\t\t\tstrUrl = \"/user/admin/insUserData.do\";\r\n");
      out.write("\t\t\t\t$(\"#inpPw\").val($(\"#inpPw2\").val());\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\telse{\r\n");
      out.write("\t\t\t\tstrUrl = \"/user/admin/updateUserData.do\";\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tvar arrKeyValue = [\"userId\",\"userPw\",\"userName\",\"userEmail\",\"userBDay\",\"userAuth\",\"userLvl\"];\r\n");
      out.write("\t\t\tfor(var intIndex = 0; intIndex<$(\".inpData\").length; intIndex++) {\r\n");
      out.write("\t\t\t\tobjData[arrKeyValue[intIndex]] = $(\".inpData\"+intIndex).val();\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\telse if(strType == \"P\") {\r\n");
      out.write("\t\t\tvar strUserPw = $(\"#inpPw\").val();\r\n");
      out.write("\t\t\tvar strUserId = $(\"#inpId\").val();\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tif(checkNullHd(strUserPw)) {\r\n");
      out.write("\t\t\t\t$(\"#inpPw\").css(\"border\",\"solid 1px red;\");\r\n");
      out.write("\t\t\t\t$(\"#ftLoading\").hide();\r\n");
      out.write("\t\t\t\treturn;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tobjData[\"userId\"] = strUserId;\r\n");
      out.write("\t\t\tobjData[\"userPw\"] = strUserPw;\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tstrUrl = \"/user/admin/updateUserPw.do\";\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\telse if(strType == \"D\") {\r\n");
      out.write("\t\t\tstrUrl = \"/user/admin/deleteUserData.do\";\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\ttype:\"POST\",\r\n");
      out.write("\t\t\turl: strUrl,\r\n");
      out.write("\t\t\tcontentType:\"application/json; charset=UTF-8\",\r\n");
      out.write("\t\t\tdata: JSON.stringify(objData),\r\n");
      out.write("\t\t\tdataType: \"JSON\",\r\n");
      out.write("\t\t\tsuccess: function(intReturnVal) {\r\n");
      out.write("\t\t\t\tif(intReturnVal == 1) {\r\n");
      out.write("\t\t\t\t\talert(\"UPDATE COMPLETED!\");\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\tif(strType == \"P\")\t$(\".modal\").modal(\"hide\");\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\tdoSelectData();\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\telse if(intReturnVal == 0) {\r\n");
      out.write("\t\t\t\t\talert(\"ERROR - USERLIST01\");\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\t$(\"#ftLoading\").hide();\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction trOnClick(strId, intDataNo) {\r\n");
      out.write("\t\tif(mStrClickable == \"Y\") {\r\n");
      out.write("\t\t\t$(\".inpData\").val(\"\");\r\n");
      out.write("\t\t\tmIntUpdtDataNo = intDataNo;\r\n");
      out.write("\t\t\t$(\".inpData\").attr(\"readonly\",false);\r\n");
      out.write("\t\t\t$(\"#btnPw\").attr(\"disabled\",false);\r\n");
      out.write("\t\t\t$(\"#inpId\").attr(\"disabled\",true);\r\n");
      out.write("\t\t\t//Background-color 설정 시작\r\n");
      out.write("\t\t\t$(\"#\"+mStrBeforeId).css(\"background-color\",mStrBeforeBG);\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tmStrBeforeId = strId;\r\n");
      out.write("\t\t\tmStrBeforeBG = $(\"#\"+strId).css(\"background-color\");\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t$(\"#\"+strId).css(\"background-color\",\"#ffe7e7\");\r\n");
      out.write("\t\t\t//Background-color 설정 끝\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tvar arrData = $(\"#\" + strId + \" td\");\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tfor(var intIndex = 0; intIndex < $(\".inpData\").length; intIndex++) {\r\n");
      out.write("\t\t\t\t$(\".inpData\"+intIndex).val(arrData[intIndex].textContent);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\telse {\r\n");
      out.write("\t\t\talert(\"Save your data first.\");\r\n");
      out.write("\t\t\treturn;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction doInsertRow() {\r\n");
      out.write("\t\tmStrClickable = \"N\";\r\n");
      out.write("\t\tmStrInsStatus = \"I\";\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(\"#\"+mStrBeforeId).css(\"background-color\",mStrBeforeBG);\r\n");
      out.write("\t\t$(\".inpData\").attr(\"readonly\",false);\r\n");
      out.write("\t\t$(\"#inpId\").attr(\"disabled\",false);\r\n");
      out.write("\t\t$(\".inpData\").val(\"\");\r\n");
      out.write("\t\t$(\"#inpAdd\").hide();\r\n");
      out.write("\t\t$(\"#btnPw\").hide();\r\n");
      out.write("\t\t$(\"#inpCancel\").show();\r\n");
      out.write("\t\t$(\"#inpSave\").show();\r\n");
      out.write("\t\t$(\"#inpPw2\").show();\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(\"#inpId\").keyup(function(){\r\n");
      out.write("\t\t\t$(\".tdId\").text($(\"#inpId\").val());\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t$(\"#inpName\").keyup(function(){\r\n");
      out.write("\t\t\t$(\".tdName\").text($(\"#inpName\").val());\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t$(\"#inpEmail\").keyup(function(){\r\n");
      out.write("\t\t\t$(\".tdEmail\").text($(\"#inpEmail\").val());\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t$(\"#inpBDay\").keyup(function(){\r\n");
      out.write("\t\t\t$(\".tdBDay\").text($(\"#inpBDay\").val());\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t$(\"#inpAuth\").change(function(){\r\n");
      out.write("\t\t\t$(\".tdAuth\").text($(\"#inpAuth option:checked\").text());\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t$(\"#inpLvl\").change(function(){\r\n");
      out.write("\t\t\t$(\".tdLvl\").text($(\"#inpLvl option:checked\").text());\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t$(\"#btnPw\").attr(\"disabled\",false);\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tdoInsertRowTr();\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction doInsertRowTr() {\r\n");
      out.write("\t\tvar arrHtml = [];\r\n");
      out.write("\t\tvar strUserId = '");
      out.print(mStrUserId);
      out.write("';\r\n");
      out.write("\t\tarrHtml.push(\"<tr class='trData trAddData' style='background-color:#ffe7e7;'>\");\r\n");
      out.write("\t\t\tarrHtml.push(\"<td class='tdTextCenter tdId'></td>\");\r\n");
      out.write("\t\t\tarrHtml.push(\"<td class='tdTextCenter tdName'></td>\");\r\n");
      out.write("\t\t\tarrHtml.push(\"<td class='tdTextCenter tdEmail'></td>\");\r\n");
      out.write("\t\t\tarrHtml.push(\"<td class='tdTextCenter tdBDay'></td>\");\r\n");
      out.write("\t\t\tarrHtml.push(\"<td class='tdTextCenter tdAuth'></td>\");\r\n");
      out.write("\t\t\tarrHtml.push(\"<td class='tdTextCenter tdLvl'></td>\");\r\n");
      out.write("\t\t\tarrHtml.push(\"<td class='tdTextCenter tdUseYn'>Y</td>\");\r\n");
      out.write("\t\t\tarrHtml.push(\"<td class='tdTextCenter'>\"+ strUserId +\"</td>\");\r\n");
      out.write("\t\t\tarrHtml.push(\"<td class='tdTextCenter'></td>\");\r\n");
      out.write("\t\t\tarrHtml.push(\"<td class='tdTextCenter'></td>\");\r\n");
      out.write("\t\t\tarrHtml.push(\"<td class='tdTextCenter'></td>\");\r\n");
      out.write("\t\t\tarrHtml.push(\"<td class='tdTextCenter'></td>\");\r\n");
      out.write("\t\t\tarrHtml.push(\"<td class='tdTextCenter'></td>\");\r\n");
      out.write("\t\tarrHtml.push(\"</tr>\");\r\n");
      out.write("\t\r\n");
      out.write("\t\t$(\"#tblUserList\").prepend(arrHtml.join(\"\"));\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction doCancel(){\r\n");
      out.write("\t\tmStrInsStatus = \"\";\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(\".trAddData\").remove();\r\n");
      out.write("\t\t$(\"#inpCancel\").hide();\r\n");
      out.write("\t\t$(\"#inpSave\").hide();\r\n");
      out.write("\t\t$(\"#inpPw2\").hide();\r\n");
      out.write("\t\t$(\"#inpAdd\").show();\r\n");
      out.write("\t\t$(\"#btnPw\").show();\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(\".inpData\").val(\"\");\r\n");
      out.write("\t\t$(\".inpData\").attr(\"readonly\",true);\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tmStrClickable = \"Y\";\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\tfunction doCheckValidation(){\r\n");
      out.write("\t\tvar boolReturnVal = true;\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(\".required\").each(function(){\r\n");
      out.write("\t\t\tconsole.log($(this).val());\r\n");
      out.write("\t\t\tif(checkNullHd($(this).val())) {\r\n");
      out.write("\t\t\t\talert(\"Check your required field(s).\");\r\n");
      out.write("\t\t\t\tboolReturnVal = false;\r\n");
      out.write("\t\t\t\treturn false;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\t//update status not insert\r\n");
      out.write("\t\t//password input is diffrent from update and insert\r\n");
      out.write("\t\tif(mStrClickable == \"N\") {\r\n");
      out.write("\t\t\tif(checkNullHd($(\".requiredPw\").val())) {\r\n");
      out.write("\t\t\t\talert(\"Check your required field(s).\");\r\n");
      out.write("\t\t\t\tboolReturnVal = false;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\treturn boolReturnVal;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t$(document).ready(function(){\r\n");
      out.write("\t\t//doCodeDetail(\"USER_RANK\");\r\n");
      out.write("\t\tdoSelectData();\r\n");
      out.write("\t});\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<div id=\"content\">\r\n");
      out.write("<div id=\"content-header\">\r\n");
      out.write("  <div id=\"breadcrumb\"> <a href=\"/main.do\" title=\"Go to Home\" class=\"tip-bottom\"><i class=\"icon-home\"></i> Home</a> <a href=\"#\" class=\"current\">Manage Users</a> </div>\r\n");
      out.write("  <h1></h1>\r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"container-fluid\">\r\n");
      out.write("  <hr>\r\n");
      out.write("  <div class=\"row-fluid\">\r\n");
      out.write("  \t<div class=\"span12\">\r\n");
      out.write("     \t\r\n");
      out.write("\t\t<form id=\"frmAdminArea\" class=\"form-horizontal\" method=\"post\" action=\"#\" name=\"basic_validate\" id=\"basic_validate\" novalidate=\"novalidate\">\r\n");
      out.write("\t\t\t<div id=\"divUserName\" class=\"span4 control-group\" style=\"border-top:1px solid #eeeeee !important;\">\r\n");
      out.write("\t\t\t\t<!-- <label class=\"control-label\">Name</label>\r\n");
      out.write("\t\t\t\t<div class=\"controls\">\r\n");
      out.write("\t\t\t\t\t<input type=\"text\" name=\"required\" id=\"inpUserName\">\r\n");
      out.write("\t\t\t\t</div> -->\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"control-group span4\" style=\"border-top:1px solid #eeeeee !important;\">\r\n");
      out.write("\t             <!-- <label class=\"control-label\">Date</label>\r\n");
      out.write("\t             <div class=\"controls\">\r\n");
      out.write("\t               <input type=\"text\" id=\"inpSDate\" data-date=\"2013-01-02\" data-date-format=\"yyyy-mm-dd\" value=\"\" class=\"datepicker span6\">\r\n");
      out.write("\t               <input type=\"text\" id=\"inpEDate\" data-date=\"2013-01-02\" data-date-format=\"yyyy-mm-dd\" value=\"\" class=\"datepicker span6\">\r\n");
      out.write("\t             </div> -->\r\n");
      out.write("           </div>\r\n");
      out.write("\t\t\t<div class=\"span3 control-group\" style=\"border-top:1px solid #eeeeee !important; padding-left:20px; margin-top:10px;\" align=\"right\">\r\n");
      out.write("\t\t\t\t<!-- <input type=\"button\" class=\"btn\" onclick=\"doSelectData();\" value=\"Search\"> -->\r\n");
      out.write("\t\t\t\t<input id=\"inpAdd\" type=\"button\" class=\"btn\" onclick=\"doInsertRow();\" value=\"Add\">\r\n");
      out.write("\t\t\t\t<input id=\"inpCancel\" type=\"button\" class=\"btn btn-danger\" onclick=\"doCancel();\" value=\"Cancel\" style=\"display:none;\">\r\n");
      out.write("\t\t\t\t<input type=\"button\" class=\"btn\" onclick=\"doUpdateData('I');\" value=\"Save\">\r\n");
      out.write("\t\t\t\t<input type=\"button\" class=\"btn\" onclick=\"doUpdateData('D');\" value=\"Delete\">\r\n");
      out.write("\t\t\t\t<!-- <input type=\"button\" class=\"btn\" onclick=\"doSelectData();\" value=\"Search\">\r\n");
      out.write("\t\t\t\t<input type=\"button\" class=\"btn\" onclick=\"doSelectData();\" value=\"Search\"> -->\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"span1\"></div>\r\n");
      out.write("\t\t</form>\r\n");
      out.write("  \t</div>\r\n");
      out.write("  </div>\r\n");
      out.write("  <div class=\"row-fluid\">\r\n");
      out.write("  \t\r\n");
      out.write(" \t<div class=\"span8\">\r\n");
      out.write("      <div class=\"widget-box\">\r\n");
      out.write("        <div class=\"widget-title\"> <span class=\"icon\"><i class=\"icon-th\"></i></span>\r\n");
      out.write("          <h5>USER LIST</h5>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"widget-content nopadding\" style=\"overflow-x: auto;\">\r\n");
      out.write("          <table class=\"table table-bordered\">\r\n");
      out.write("\t        <thead>\r\n");
      out.write("\t            <tr>\r\n");
      out.write("\t              <!-- <th>USER NO</th> -->\r\n");
      out.write("\t              <th>ID</th>\r\n");
      out.write("\t              <th style=\"display:none;\">PW</th>\r\n");
      out.write("\t              <th>NAME</th>\r\n");
      out.write("\t              <th>EMAIL</th>\r\n");
      out.write("\t              <th>B-DAY</th>\r\n");
      out.write("\t              <th>AUTH</th>\r\n");
      out.write("     \t          <th>LVL</th>\r\n");
      out.write("     \t          <th>DEALER INFO</th>\r\n");
      out.write("\t              <th>USE Y/N</th>\r\n");
      out.write("\t              <th>REG ID</th>\r\n");
      out.write("\t              <th>REG IP</th>\r\n");
      out.write("\t              <th style=\"min-width:90px;\">REG DATE</th>\r\n");
      out.write("\t              <th style=\"min-width:\">UPDT ID</th>\r\n");
      out.write("\t              <th style=\"min-width:\">UPDT IP</th>\r\n");
      out.write("\t              <th style=\"min-width:90px;\">UPDT DATE</th>\r\n");
      out.write("\t            </tr>\r\n");
      out.write("\t        </thead>\r\n");
      out.write("\t\t\t<tbody id=\"tblUserList\">\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t</tbody>\r\n");
      out.write("          </table>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      <input id=\"btnMore\" type=\"button\" class=\"btn btn-large span12\" onclick=\"doSelectData('M');\" value=\"More\">\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"span4\">\r\n");
      out.write("      <div class=\"widget-box\">\r\n");
      out.write("        <div class=\"widget-title\"> <span class=\"icon\"> <i class=\"icon-align-justify\"></i> </span>\r\n");
      out.write("          <h5>USER INFORMATION</h5>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"widget-content nopadding\">\r\n");
      out.write("          <form action=\"#\" method=\"get\" class=\"form-horizontal\">\r\n");
      out.write("            <div class=\"control-group\">\r\n");
      out.write("              <label class=\"control-label\"><span class=\"requiredFieldM9\">*</span>ID :</label>\r\n");
      out.write("              <div class=\"controls\">\r\n");
      out.write("                <input id=\"inpId\" type=\"text\" class=\"span11 required inpData inpData0\" placeholder=\"ID\" disabled maxlength=\"20\"/>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"control-group\">\r\n");
      out.write("              <label class=\"control-label\"><span class=\"requiredFieldM9\">*</span>PASSWORD :</label>\r\n");
      out.write("              <div class=\"controls\">\r\n");
      out.write("              \t<input id=\"inpPw2\" type=\"password\" class=\"span11 requiredPw inpData\" placeholder=\"PASSWORD\" maxlength=\"12\" style=\"display:none;\"/>\r\n");
      out.write("                <button id=\"btnPw\" data-toggle=\"modal\" data-target=\"#mdEditPassword\"  class=\"span11 inpData\" value=\"EDIT PASSWORD\" style=\"margin-left:0px;\" disabled>EDIT PASSWORD</button>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"control-group\">\r\n");
      out.write("              <label class=\"control-label\"><span class=\"requiredFieldM9\">*</span>NAME :</label>\r\n");
      out.write("              <div class=\"controls\">\r\n");
      out.write("                <input id=\"inpName\" type=\"text\" class=\"span11 required inpData inpData2\" placeholder=\"NAME\" maxlength=\"20\"/>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"control-group\">\r\n");
      out.write("              <label class=\"control-label\">EMAIL :</label>\r\n");
      out.write("              <div class=\"controls\">\r\n");
      out.write("                <input id=\"inpEmail\" type=\"text\"  class=\"span11 inpData inpData3\" placeholder=\"EMAIL\" maxlength=\"50\"/>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"control-group\">\r\n");
      out.write("              <label class=\"control-label\">B-DAY :</label>\r\n");
      out.write("              <div class=\"controls\">\r\n");
      out.write("                <input id=\"inpBDay\" type=\"text\"  class=\"span11 inpData inpData4\" placeholder=\"B-DAY\" maxlength=\"10\"/>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"control-group\">\r\n");
      out.write("              <label class=\"control-label\"><span class=\"requiredFieldM9\">*</span>AUTH :</label>\r\n");
      out.write("              <div class=\"controls\">\r\n");
      out.write("              \t<select id=\"inpAuth\" class=\"span11 required inpData inpData5\">\r\n");
      out.write("              \t\t<option value=\"\">AUTH</option>\r\n");
      out.write("\t\t\t\t\t");
      if (_jspx_meth_c_005fforEach_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t\t</select>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"control-group\">\r\n");
      out.write("              <label class=\"control-label\"><span class=\"requiredFieldM9\">*</span>LEVEL :</label>\r\n");
      out.write("              <div class=\"controls\">\r\n");
      out.write("              \t<select id=\"inpLvl\" class=\"span11 required inpData inpData6\">\r\n");
      out.write("              \t\t<option value=\"\">LEVEL</option>\r\n");
      out.write("\t\t\t\t\t");
      if (_jspx_meth_c_005fforEach_005f2(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t\t</select>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </form>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("</div></div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<!-- Modal -->\r\n");
      out.write("<div class=\"modal fade\" id=\"mdEditPassword\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"exampleModalLabel\" aria-hidden=\"true\">\r\n");
      out.write("  <div class=\"modal-dialog\" role=\"document\">\r\n");
      out.write("    <div class=\"modal-content\">\r\n");
      out.write("      <div class=\"modal-header\">\r\n");
      out.write("        <h5 class=\"modal-title\" id=\"exampleModalLabel\">EDIT PASSWORD</h5>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"modal-body\">\r\n");
      out.write("        <div class=\"control-group\">\r\n");
      out.write("            <label class=\"control-label\"><span class=\"requiredFieldM9\">*</span>PASSWORD :</label>\r\n");
      out.write("            <div class=\"controls\">\r\n");
      out.write("              <input id=\"inpPw\" type=\"password\"  class=\"span3 inpData inpData1\" placeholder=\"PASSWORD\" maxlength=\"12\"/>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"modal-footer\">\r\n");
      out.write("        <button type=\"button\" class=\"btn btn-secondary\" data-dismiss=\"modal\">Close</button>\r\n");
      out.write("        <button type=\"button\" class=\"btn btn-primary\" onclick=\"doUpdateData('P')\">Save</button>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<button id=\"btnDealerInfo\" data-toggle=\"modal\" data-target=\"#mdDealerInfo\"  class=\"span11 inpData\" value=\"DEALER INFO\" style=\"margin-left:0px; display:none;\"></button>\r\n");
      out.write("\r\n");
      out.write("<!-- Modal -->\r\n");
      out.write("<div class=\"modal fade\" id=\"mdDealerInfo\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"exampleModalLabel\" aria-hidden=\"true\">\r\n");
      out.write("  <div class=\"modal-dialog\" role=\"document\">\r\n");
      out.write("    <div class=\"modal-content\">\r\n");
      out.write("      <div class=\"modal-header\">\r\n");
      out.write("        <h5 class=\"modal-title\" id=\"exampleModalLabel\">DEALER INFO</h5>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div id=\"modalBody\" class=\"modal-body\">\r\n");
      out.write("      \t\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"modal-footer\">\r\n");
      out.write("        <button type=\"button\" class=\"btn btn-secondary\" data-dismiss=\"modal\">Close</button>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/views/include/footer.jsp", out, false);
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /WEB-INF/views/user/userList.jsp(48,2) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("idx");
      // /WEB-INF/views/user/userList.jsp(48,2) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/user/userList.jsp(48,2) '${commCodeList}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${commCodeList}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      // /WEB-INF/views/user/userList.jsp(48,2) name = varStatus type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVarStatus("status");
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("\t\t\tif(\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${idx.MAST_NAME}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\" == strCommName && \"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${idx.CODE}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\" == strCommCode) {\r\n");
            out.write("\t\t\t\tstrReturnVal = \"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${idx.NAME}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\";\r\n");
            out.write("\t\t\t}\r\n");
            out.write("\t\t");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f1 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f1_reused = false;
    try {
      _jspx_th_c_005fforEach_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f1.setParent(null);
      // /WEB-INF/views/user/userList.jsp(556,5) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setVar("idx");
      // /WEB-INF/views/user/userList.jsp(556,5) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/user/userList.jsp(556,5) '${commCodeList}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${commCodeList}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int[] _jspx_push_body_count_c_005fforEach_005f1 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f1 = _jspx_th_c_005fforEach_005f1.doStartTag();
        if (_jspx_eval_c_005fforEach_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("\t\t\t\t\t\t");
            if (_jspx_meth_c_005fset_005f0(_jspx_th_c_005fforEach_005f1, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f1))
              return true;
            out.write("\r\n");
            out.write("\t\t\t\t\t\t");
            if (_jspx_meth_c_005fif_005f0(_jspx_th_c_005fforEach_005f1, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f1))
              return true;
            out.write("\r\n");
            out.write("\t\t\t\t\t");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f1.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f1[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f1.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f1.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f1);
      _jspx_th_c_005fforEach_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fset_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f1, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f1)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f0_reused = false;
    try {
      _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f1);
      // /WEB-INF/views/user/userList.jsp(557,6) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setVar("userAuth");
      // /WEB-INF/views/user/userList.jsp(557,6) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setValue(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/user/userList.jsp(557,6) '${idx.MAST_NAME}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${idx.MAST_NAME}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
      if (_jspx_th_c_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
      _jspx_th_c_005fset_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f1, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f1)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f1);
      // /WEB-INF/views/user/userList.jsp(558,6) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${userAuth eq 'USER_AUTH'}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\t\t\t\t\t<option id=\"optAuth");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${idx.CODE}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\" value=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${idx.CODE}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write('"');
          out.write('>');
          out.write(' ');
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${idx.NAME}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</option>\r\n");
          out.write("\t\t\t\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f2 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f2_reused = false;
    try {
      _jspx_th_c_005fforEach_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f2.setParent(null);
      // /WEB-INF/views/user/userList.jsp(570,5) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f2.setVar("idx");
      // /WEB-INF/views/user/userList.jsp(570,5) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f2.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/user/userList.jsp(570,5) '${commCodeList}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${commCodeList}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int[] _jspx_push_body_count_c_005fforEach_005f2 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f2 = _jspx_th_c_005fforEach_005f2.doStartTag();
        if (_jspx_eval_c_005fforEach_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("\t\t\t\t\t\t");
            if (_jspx_meth_c_005fset_005f1(_jspx_th_c_005fforEach_005f2, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f2))
              return true;
            out.write("\r\n");
            out.write("\t\t\t\t\t\t");
            if (_jspx_meth_c_005fif_005f1(_jspx_th_c_005fforEach_005f2, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f2))
              return true;
            out.write("\r\n");
            out.write("\t\t\t\t\t");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f2.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f2[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f2.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f2.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f2);
      _jspx_th_c_005fforEach_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fset_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f2, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f2)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f1 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f1_reused = false;
    try {
      _jspx_th_c_005fset_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f2);
      // /WEB-INF/views/user/userList.jsp(571,6) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f1.setVar("userLvl");
      // /WEB-INF/views/user/userList.jsp(571,6) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f1.setValue(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/user/userList.jsp(571,6) '${idx.MAST_NAME}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${idx.MAST_NAME}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f1 = _jspx_th_c_005fset_005f1.doStartTag();
      if (_jspx_th_c_005fset_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f1);
      _jspx_th_c_005fset_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f2, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f2)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f1_reused = false;
    try {
      _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f2);
      // /WEB-INF/views/user/userList.jsp(572,6) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${userLvl eq 'USER_LVL'}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
      if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\t\t\t\t\t<option id=\"optLvl");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${idx.CODE}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\" value=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${idx.CODE}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write('"');
          out.write('>');
          out.write(' ');
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${idx.NAME}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</option>\r\n");
          out.write("\t\t\t\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      _jspx_th_c_005fif_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f1_reused);
    }
    return false;
  }
}
