/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.30
 * Generated at: 2018-04-28 09:45:26 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class signIn_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\t<head>\r\n");
      out.write("        <title>LANDS</title><meta charset=\"UTF-8\" />\r\n");
      out.write("        <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\" />\r\n");
      out.write("\t\t<link rel=\"stylesheet\" href=\"/resources/css/bootstrap.min.css\" />\r\n");
      out.write("\t\t<link rel=\"stylesheet\" href=\"/resources/css/bootstrap-responsive.min.css\" />\r\n");
      out.write("        <link rel=\"stylesheet\" href=\"/resources/css/matrix-login.css\" />\r\n");
      out.write("        <link href=\"/resources/font-awesome/css/font-awesome.css\" rel=\"stylesheet\" />\r\n");
      out.write("\t\t<link href='http://fonts.googleapis.com/css?family=Open+Sans:400,700,800' rel='stylesheet' type='text/css'>\r\n");
      out.write("    </head>\r\n");
      out.write("\r\n");
      out.write("    <body>\r\n");
      out.write("        <div id=\"loginbox\">\r\n");
      out.write("            <form id=\"loginform\" class=\"form-vertical\" action=\"index.html\">\r\n");
      out.write("\t\t\t\t<div class=\"control-group normal_text\"> <h3><img src=\"/resources/img/lands_logo_03.png\" alt=\"Logo\" style=\"height:25px; width:180px;\"/></h3></div>\r\n");
      out.write("                <div class=\"control-group\">\r\n");
      out.write("                    <div class=\"controls\">\r\n");
      out.write("                        <div class=\"main_input_box\">\r\n");
      out.write("                            <span class=\"add-on bg_lg\"><i class=\"icon-user\"> </i></span><input id=\"userId\" type=\"text\" placeholder=\"Username\" />\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"control-group\">\r\n");
      out.write("                    <div class=\"controls\">\r\n");
      out.write("                        <div class=\"main_input_box\">\r\n");
      out.write("                            <span class=\"add-on bg_ly\"><i class=\"icon-lock\"></i></span><input id=\"userPw\" type=\"password\" placeholder=\"Password\" />\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"form-actions\">\r\n");
      out.write("                    <!-- <span class=\"pull-left\"><a href=\"#\" class=\"flip-link btn btn-info\" id=\"to-recover\">Lost password?</a></span> -->\r\n");
      out.write("                    <span style=\"margin-left:45%;\"><a type=\"button\" href=\"javascript:signIn();\" class=\"btn btn-success\" /> Sign In</a></span>\r\n");
      out.write("                </div>\r\n");
      out.write("            </form>\r\n");
      out.write("            <!-- <form id=\"recoverform\" action=\"#\" class=\"form-vertical\">\r\n");
      out.write("\t\t\t\t<p class=\"normal_text\">Enter your e-mail address below and we will send you instructions how to recover a password.</p>\r\n");
      out.write("                    <div class=\"controls\">\r\n");
      out.write("                        <div class=\"main_input_box\">\r\n");
      out.write("                            <span class=\"add-on bg_lo\"><i class=\"icon-envelope\"></i></span><input type=\"text\" placeholder=\"E-mail address\" />\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                <div class=\"form-actions\">\r\n");
      out.write("                    <span class=\"pull-left\"><a href=\"#\" class=\"flip-link btn btn-success\" id=\"to-login\">&laquo; Back to login</a></span>\r\n");
      out.write("                    <span class=\"pull-right\"><a class=\"btn btn-info\"/>Reecover</a></span>\r\n");
      out.write("                </div>\r\n");
      out.write("            </form> -->\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("        <script src=\"/resources/js/jquery.min.js\"></script>\r\n");
      out.write("        <script src=\"/resources/js/matrix.login.js\"></script>\r\n");
      out.write("        <script>\r\n");
      out.write("\t    \tfunction signIn() {\r\n");
      out.write("\t    \t\tvar objData = {};\r\n");
      out.write("\t    \t\tvar strUserId = $(\"#userId\").val();\r\n");
      out.write("\t    \t\tvar strUserPw = $(\"#userPw\").val();\r\n");
      out.write("\t    \t\t\r\n");
      out.write("\t    \t\tif(checkNull(strUserId)) {\r\n");
      out.write("\t    \t\t\talert(\"Check your ID, please.\");\r\n");
      out.write("\t    \t\t\treturn;\r\n");
      out.write("\t    \t\t}\r\n");
      out.write("\t    \t\telse if(checkNull(strUserPw)) {\r\n");
      out.write("\t    \t\t\talert(\"Check your Password, please.\");\r\n");
      out.write("\t    \t\t\treturn;\r\n");
      out.write("\t    \t\t}\r\n");
      out.write("\t    \t\t\r\n");
      out.write("\t    \t\tobjData[\"userId\"] = strUserId;\r\n");
      out.write("\t    \t\tobjData[\"userPw\"] = strUserPw;\r\n");
      out.write("\t    \t\t\r\n");
      out.write("\t    \t\t$.ajax({\r\n");
      out.write("\t    \t\t\ttype: \"POST\",\r\n");
      out.write("\t    \t\t\turl: \"/auth/signIn.do\",\r\n");
      out.write("\t    \t\t\tcontentType: \"application/json; charset=UTF-8\",\r\n");
      out.write("\t    \t\t\tdata: JSON.stringify(objData),\r\n");
      out.write("\t    \t\t\tdataType: \"json\",\r\n");
      out.write("\t    \t\t\tsuccess: function(intReturnVal) {\r\n");
      out.write("\t    \t\t\t\tif(intReturnVal == 0) {\r\n");
      out.write("\t    \t\t\t\t\talert(\"Check your password or id, please.\");\r\n");
      out.write("\t    \t\t\t\t\t\r\n");
      out.write("\t    \t\t\t\t\t$(\"#userPw\").val(\"\");\r\n");
      out.write("\t    \t\t\t\t}\r\n");
      out.write("\t    \t\t\t\telse {\r\n");
      out.write("\t    \t\t\t\t\tlocation.href = \"/main.do\";\r\n");
      out.write("\t    \t\t\t\t}\r\n");
      out.write("\t    \t\t\t}\r\n");
      out.write("\t    \t\t});\r\n");
      out.write("\t    \t}\r\n");
      out.write("\t    \t\r\n");
      out.write("\t    \tfunction checkNull(strValue) {\r\n");
      out.write("\t    \t\tif(strValue != null && strValue != \"\" && strValue != \"undefined\")\treturn false;\r\n");
      out.write("\t    \t\treturn true;\r\n");
      out.write("\t    \t}\r\n");
      out.write("\t    \t\r\n");
      out.write("\t    \t$(document).ready(function(){\r\n");
      out.write("\t    \t\t$(\"#userId\").keyup(function(e){\r\n");
      out.write("\t    \t\t\tif(e.keyCode == 13) {\r\n");
      out.write("\t    \t\t\t\tsignIn();\r\n");
      out.write("\t    \t\t\t}\r\n");
      out.write("\t    \t\t});\r\n");
      out.write("\t    \t\t$(\"#userPw\").keyup(function(e){\r\n");
      out.write("\t    \t\t\tif(e.keyCode == 13) {\r\n");
      out.write("\t    \t\t\t\tsignIn();\r\n");
      out.write("\t    \t\t\t}\r\n");
      out.write("\t    \t\t});\r\n");
      out.write("\t    \t\t$(\"#userId\").focus();\r\n");
      out.write("\t    \t});\r\n");
      out.write("    \t</script>\r\n");
      out.write("    \r\n");
      out.write("    </body>\r\n");
      out.write("\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
